# Generated by Django 4.2.7 on 2023-11-07 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_family'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
